Traceback (most recent call last):
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/hadiji/anaconda3/envs/py39/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('Batch size : ', batch_size)

losses = train(net, 
    trainloader,
    N_passes=50,  
    lr=0.01)

torch.save(net.state_dict(), 'models/trained_net.pt')

plt.ylim(0, 1.1 * np.max(losses))
plt.plot(losses)
plt.grid(alpha=.3)
------------------

----- stdout -----
Batch size :  32
----- stdout -----
Number of gradient steps 3150
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[6], line 8[0m
[1;32m      1[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mBatch size : [39m[38;5;124m'[39m, batch_size)
[1;32m      3[0m losses [38;5;241m=[39m train(net, 
[1;32m      4[0m     trainloader,
[1;32m      5[0m     N_passes[38;5;241m=[39m[38;5;241m50[39m,  
[1;32m      6[0m     lr[38;5;241m=[39m[38;5;241m0.01[39m)
[0;32m----> 8[0m [43mtorch[49m[38;5;241;43m.[39;49m[43msave[49m[43m([49m[43mnet[49m[38;5;241;43m.[39;49m[43mstate_dict[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mmodels/trained_net.pt[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     10[0m plt[38;5;241m.[39mylim([38;5;241m0[39m, [38;5;241m1.1[39m [38;5;241m*[39m np[38;5;241m.[39mmax(losses))
[1;32m     11[0m plt[38;5;241m.[39mplot(losses)

File [0;32m~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/serialization.py:628[0m, in [0;36msave[0;34m(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization, _disable_byteorder_record)[0m
[1;32m    625[0m _check_save_filelike(f)
[1;32m    627[0m [38;5;28;01mif[39;00m _use_new_zipfile_serialization:
[0;32m--> 628[0m     [38;5;28;01mwith[39;00m [43m_open_zipfile_writer[49m[43m([49m[43mf[49m[43m)[49m [38;5;28;01mas[39;00m opened_zipfile:
[1;32m    629[0m         _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
[1;32m    630[0m         [38;5;28;01mreturn[39;00m

File [0;32m~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/serialization.py:502[0m, in [0;36m_open_zipfile_writer[0;34m(name_or_buffer)[0m
[1;32m    500[0m [38;5;28;01melse[39;00m:
[1;32m    501[0m     container [38;5;241m=[39m _open_zipfile_writer_buffer
[0;32m--> 502[0m [38;5;28;01mreturn[39;00m [43mcontainer[49m[43m([49m[43mname_or_buffer[49m[43m)[49m

File [0;32m~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/serialization.py:473[0m, in [0;36m_open_zipfile_writer_file.__init__[0;34m(self, name)[0m
[1;32m    471[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(torch[38;5;241m.[39m_C[38;5;241m.[39mPyTorchFileWriter([38;5;28mself[39m[38;5;241m.[39mfile_stream))
[1;32m    472[0m [38;5;28;01melse[39;00m:
[0;32m--> 473[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([43mtorch[49m[38;5;241;43m.[39;49m[43m_C[49m[38;5;241;43m.[39;49m[43mPyTorchFileWriter[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m)[49m)

[0;31mRuntimeError[0m: Parent directory models does not exist.

